{
 "title": "Thread-CoAP App",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n    SELECT\n        id,\n        set_temperature AS Set_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Temperature\nFROM converted\nORDER BY id DESC;\n",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        id,\n        set_temperature AS Set_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Temperature\nFROM converted\nORDER BY id DESC;\n",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_temperature AS Measured_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT datetime, Measured_Temperature\nFROM converted\nORDER BY id DESC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_temperature AS Measured_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT datetime, Measured_Temperature\nFROM converted\nORDER BY id DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Illuminance Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n    SELECT\n        id,\n        set_illuminance AS Set_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Illuminance\nFROM converted\nORDER BY id DESC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        id,\n        set_illuminance AS Set_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Illuminance\nFROM converted\nORDER BY id DESC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_illuminance AS Measured_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT datetime, Measured_Illuminance\nFROM converted\nORDER BY id DESC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_illuminance AS Measured_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT datetime, Measured_Illuminance\nFROM converted\nORDER BY id DESC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  { "title": "Time Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n    SELECT\n        measured_temperature AS Measured_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT datetime, Measured_Temperature\nFROM converted\nORDER BY datetime ASC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        measured_temperature AS Measured_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT datetime, Measured_Temperature\nFROM converted\nORDER BY datetime ASC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "WITH converted AS (\n    SELECT\n        set_temperature AS Set_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Temperature\nFROM converted\nORDER BY datetime ASC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        set_temperature AS Set_Temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Temperature\nFROM converted\nORDER BY datetime ASC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "WITH converted AS (\n    SELECT\n        sent_temperature_correction AS correction,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT datetime, correction\nFROM converted",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        sent_temperature_correction AS correction,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT datetime, correction\nFROM converted",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "Illuminance over Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "queryText": "WITH converted AS (\n    SELECT\n        measured_illuminance AS Measured_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT datetime, Measured_Illuminance\nFROM converted\nORDER BY datetime ASC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        measured_illuminance AS Measured_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT datetime, Measured_Illuminance\nFROM converted\nORDER BY datetime ASC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "WITH converted AS (\n    SELECT\n        set_illuminance AS Set_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Illuminance\nFROM converted\nORDER BY datetime ASC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        set_illuminance AS Set_Illuminance,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT datetime, Set_Illuminance\nFROM converted\nORDER BY datetime ASC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    },
    {
     "queryText": "WITH converted AS (\n    SELECT\n        sent_illuminance_correction AS correction,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT datetime, correction\nFROM converted\nORDER BY datetime ASC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        sent_illuminance_correction AS correction,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT datetime, correction\nFROM converted\nORDER BY datetime ASC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "WEB_MANAGER Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "queryText": "WITH converted AS (\n    SELECT\n        id,\n        set_illuminance,\n        set_temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT id, datetime, set_temperature, set_illuminance\nFROM converted\nORDER BY datetime DESC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        id,\n        set_illuminance,\n        set_temperature,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        WEB_MANAGER\n)\nSELECT id, datetime, set_temperature, set_illuminance\nFROM converted\nORDER BY datetime DESC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "DIMMER Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 19 },
   "targets": [
    {
     "queryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_illuminance,\n        sent_illuminance_correction,\n        src_IP,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT id, datetime, measured_illuminance, sent_illuminance_correction, src_IP\nFROM converted\nORDER BY id DESC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_illuminance,\n        sent_illuminance_correction,\n        src_IP,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        DIMMER\n)\nSELECT id, datetime, measured_illuminance, sent_illuminance_correction, src_IP\nFROM converted\nORDER BY id DESC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  },
  {
   "title": "HEATER Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 19 },
   "targets": [
    {
     "queryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_temperature,\n        sent_temperature_correction,\n        src_IP,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT id, datetime, measured_temperature, sent_temperature_correction, src_IP\nFROM converted\nORDER BY id DESC;",
     "rawQueryText": "WITH converted AS (\n    SELECT\n        id,\n        measured_temperature,\n        sent_temperature_correction,\n        src_IP,\n        strftime('%Y-%m-%dT%H:%M:%SZ', time) AS datetime\n    FROM\n        HEATER\n)\nSELECT id, datetime, measured_temperature, sent_temperature_correction, src_IP\nFROM converted\nORDER BY id DESC;",
     "timeColumns": [
      "time",
      "ts",
      "datetime"
     ]
    }
   ]
  }
 ]
}